import React from "react";
import PrivateRoute from '../../../components/PrivateRoute'
import Successpopup from "../../../components/SuccessPopup"
import { Box, Button, FormControl, Grid, MenuItem, Select, TextField, Typography } from "@mui/material";
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import ExpandMoreOutlinedIcon from "@mui/icons-material/ExpandMoreOutlined";
import test from '../../../assets/images/test.svg'

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function CustomTabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ pt: 3}}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

export default function AssetDetails() {
  const [value, setValue] = React.useState(0);
  const [answers, setAnswers] = React.useState("");
  const Placeholder = ({ children }: any) => {
    return <div>{children}</div>;
  };
  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };
  const [openSuccess, setSuccessOpen] = React.useState(false);

  return (
    <PrivateRoute>
      <Box className="main-padding">
        <Successpopup open={openSuccess} close={() => setSuccessOpen(false)} />
        <Box className="title-main" sx={{ borderBottom: '3px solid #F3F3F3', paddingBottom: '1rem' }}>
          <Box>
            <Typography>Asset details</Typography>
            <Typography className="sub-text">Edit your assets and can view its usage history.</Typography>
          </Box>
        </Box>
        <Box sx={{ width: '100%', marginTop: '1rem' }}>
          <Box sx={{ borderBottom: 0 }}>
            <Tabs value={value} onChange={handleChange} variant="scrollable"
              scrollButtons="auto"
              allowScrollButtonsMobile aria-label="tabs-common" className='tabs-common' >
              <Tab label="Edit details" {...a11yProps(0)} />
              <Tab label="History" {...a11yProps(1)} />
            </Tabs>
          </Box>
          <CustomTabPanel value={value} index={0}>
            <Grid container spacing={2} sx={{ width: '100%', m: 0 }}>
              <Grid item xs={12} sm={12} md={4} lg={3} xl={3} sx={{ padding: '0px !important', paddingRight: { xs: '0px !important', md: '30px !important' } }}>
                <Box>
                  <Box sx={{ textAlign: 'center' }}>
                    <img src={test} alt="test" className="dynamic-img" />
                  </Box>
                  <Box className='edit-profile-btn' sx={{ mt: 3, mb: 3, pb: '0px !important' }}>
                    <Button>Upload photo</Button>
                  </Box>
                </Box>
              </Grid>
              <Grid item xs={12} sm={12} md={8} lg={6} xl={5} sx={{ padding: '0px !important', paddingTop: { xs: '30px !important', md: '0px !important' } }}>
                <Box>
                  <Grid container spacing={2} className='asset-popup'>
                    <Grid item xs={12} sm={12} md={12} lg={12}>
                      <Box>
                        <label>Name</label>
                        <TextField
                          margin="normal"
                          required
                          fullWidth
                          id="name"
                          name="name"
                          autoComplete="name"
                          autoFocus
                          InputLabelProps={{ shrink: false }}
                          placeholder="Assets name"
                        />
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={2} className='asset-popup'>
                    <Grid item xs={12} sm={12} md={12} lg={12}>
                      <Box className='asset-id'>
                        <label>Asset Id (autogenerated)</label>
                        <TextField
                          margin="normal"
                          required
                          fullWidth
                          id="Email"
                          name="Email"
                          autoComplete="Email"
                          autoFocus
                          InputLabelProps={{ shrink: false }}
                          placeholder="Asset Id"
                        />
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={2} className='asset-popup calender-sec'>
                    <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingRight: { sm: '1rem !important' } }}>
                      <Box>
                        <label>Purchase date</label>
                        <LocalizationProvider dateAdapter={AdapterDayjs}>
                          <DatePicker format="DD/MM/YYYY" />
                        </LocalizationProvider>
                      </Box>
                    </Grid>
                    <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingLeft: { sm: '1rem !important' }, paddingTop: { xs: '0rem !important', sm: '1rem !important' } }}>
                      <Box>
                        <label>Guaranty/warranty/expiry date</label>
                        <LocalizationProvider dateAdapter={AdapterDayjs}>
                          <DatePicker format="DD/MM/YYYY" />
                        </LocalizationProvider>
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={2} className='asset-popup'>
                    <Grid item xs={12} sm={12} md={12} lg={12}>
                      <Box>
                        <label style={{ display: 'block' }}>Organisation</label>
                        <FormControl sx={{ width: '100%' }}>
                          <Select
                            labelId="tselect-popup-label"
                            id="select-popup"
                            value={answers}
                            displayEmpty
                            IconComponent={ExpandMoreOutlinedIcon}
                            onChange={event => setAnswers(event.target.value)}
                            renderValue={
                              answers !== "" ? undefined : () => <Placeholder>Organisation</Placeholder>
                            }
                          >
                            <MenuItem value={"1"}>1</MenuItem>
                            <MenuItem value={"2"}>2</MenuItem>
                            <MenuItem value={"3"}>3</MenuItem>
                          </Select>
                        </FormControl>
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={2} className='asset-popup'>
                    <Grid item xs={12} sm={12} md={12} lg={12}>
                      <Box>
                        <label style={{ display: 'block' }}>Department/s</label>
                        <FormControl sx={{ width: '100%' }}>
                          <Select
                            labelId="tselect-popup-label"
                            id="select-popup"
                            value={answers}
                            displayEmpty
                            IconComponent={ExpandMoreOutlinedIcon}
                            onChange={event => setAnswers(event.target.value)}
                            renderValue={
                              answers !== "" ? undefined : () => <Placeholder>Select department</Placeholder>
                            }
                          >
                            <MenuItem value={"1"}>1</MenuItem>
                            <MenuItem value={"2"}>2</MenuItem>
                            <MenuItem value={"3"}>3</MenuItem>
                          </Select>
                        </FormControl>
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={2} className='asset-popup'>
                    <Grid item xs={12} sm={12} md={12} lg={12}>
                      <Box>
                        <label style={{ display: 'block' }}>Laboratory/ies</label>
                        <FormControl sx={{ width: '100%' }}>
                          <Select
                            labelId="tselect-popup-label"
                            id="select-popup"
                            value={answers}
                            displayEmpty
                            IconComponent={ExpandMoreOutlinedIcon}
                            onChange={event => setAnswers(event.target.value)}
                            renderValue={
                              answers !== "" ? undefined : () => <Placeholder>Select lab</Placeholder>
                            }
                          >
                            <MenuItem value={"1"}>1</MenuItem>
                            <MenuItem value={"2"}>2</MenuItem>
                            <MenuItem value={"3"}>3</MenuItem>
                          </Select>
                        </FormControl>
                      </Box>
                    </Grid>
                  </Grid>
                  <Grid container spacing={2} className='asset-popup'>
                    <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingRight: { sm: '1rem !important' } }}>
                      <Box>
                        <label style={{ display: 'block' }}>Status</label>
                        <FormControl sx={{ width: '100%' }}>
                          <Select
                            labelId="tselect-popup-label"
                            id="select-popup"
                            value={answers}
                            displayEmpty
                            IconComponent={ExpandMoreOutlinedIcon}
                            onChange={event => setAnswers(event.target.value)}
                            renderValue={
                              answers !== "" ? undefined : () => <Placeholder>Select status</Placeholder>
                            }
                          >
                            <MenuItem value={"1"}>1</MenuItem>
                            <MenuItem value={"2"}>2</MenuItem>
                            <MenuItem value={"3"}>3</MenuItem>
                          </Select>
                        </FormControl>
                      </Box>
                    </Grid>
                    <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingLeft: { sm: '1rem !important' }, paddingTop: { xs: '0rem !important', sm: '1rem !important' } }}>
                      <Box>
                        <label style={{ display: 'block' }}>Availability</label>
                        <FormControl sx={{ width: '100%' }}>
                          <Select
                            labelId="tselect-popup-label"
                            id="select-popup"
                            value={answers}
                            displayEmpty
                            IconComponent={ExpandMoreOutlinedIcon}
                            onChange={event => setAnswers(event.target.value)}
                            renderValue={
                              answers !== "" ? undefined : () => <Placeholder>Select availability</Placeholder>
                            }
                          >
                            <MenuItem value={"1"}>1</MenuItem>
                            <MenuItem value={"2"}>2</MenuItem>
                            <MenuItem value={"3"}>3</MenuItem>
                          </Select>
                        </FormControl>
                      </Box>
                    </Grid>
                  </Grid>
                </Box>
              </Grid>
            </Grid>
            <Box className="edit-details">
              <Button type="submit" variant="contained" className="cancel-btn">Back</Button>
              <Button type="submit" variant="contained" className="add-btn">Save</Button>
            </Box>
          </CustomTabPanel>
          <CustomTabPanel value={value} index={1}>
            <Box className="asset-id-name">
              <img src={test} alt="test" className="dynamic-img" />
              <Box className='asset-name'>
                <Typography>Asset ID</Typography>
                <Typography>Asset name</Typography>
              </Box>
            </Box>
          </CustomTabPanel>
        </Box>
      </Box>
    </PrivateRoute>
  );
}