import React from 'react'
import Dialog from "@mui/material/Dialog";
import { Box, Typography, Grid, TextField, FormControl, Select, MenuItem, Button } from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import ExpandMoreOutlinedIcon from "@mui/icons-material/ExpandMoreOutlined";
import Avatars from "../../assets/images/Avatars.svg";
import AddIcon from '@mui/icons-material/Add';
import AddPeoplePopup from "../../components/AddPeoplePopup";

const RunzForm = React.forwardRef(({ open, close, closeFormPopup, openConfirmationPopup, submitFormPopup }: any, ref) => {
    // const [openDlg2Dialog, setDialog2Open] = React.useState(false);
    // const [openSuccess, setSuccessOpen] = React.useState(false);
    const [answers, setAnswers] = React.useState("");

    const Placeholder = ({ children }: any) => {
        return <div>{children}</div>;
    };
    const [runzOpen, setRunzOpen] = React.useState(false);
    const [runCreate, setRunzCreate] = React.useState(false)
    React.useImperativeHandle(ref, () => ({
        open(state: any) {
            setRunzCreate(state);
        },
    }));


    // const handleAddButtonClick = () => {
    //     setSuccessOpen(true);
    //     closeFormPopup(false) 
    //     setTimeout(() => {
    //       setSuccessOpen(false);
    //     }, 3000);
    //   };
    //   const handleConfirmationYes = () => {
    //     setDialog2Open(false);
    //     closeFormPopup(false)
    //   };

    return (
        <div>
            {/* <Confirmationpopup
              ref={confirmationPopupRef}
              confirmationDone={handleConfirmationDone}
                // open={openDlg2Dialog}
                // close={() => setDialog2Open(false)}
                // handleConfirmationYes={handleConfirmationYes}
            />
            <Successpopup open={openSuccess} type={"Runz"} close={() => setSuccessOpen(false)} /> */}
            <Dialog
                open={runCreate}
                keepMounted
                onClose={() => closeFormPopup(false)}
                aria-labelledby="add-new-asset-title"
                aria-describedby="add-new-asset"
                fullWidth
                maxWidth="md"
                className="popup-outer"
            >
                <Box className="popup-section">
                    <Box className="title-popup">
                        <Typography>Create new Runz</Typography>
                        <CloseIcon onClick={() => closeFormPopup(false)} />
                    </Box>
                    <Box>
                        <Grid container spacing={2} className='asset-popup calender-sec'>
                            <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingRight: { sm: '1rem !important' } }}>
                                <Box>
                                    <label style={{ display: 'block' }}>Procedure ID (autogenerated)</label>
                                    <TextField
                                        margin="normal"
                                        required
                                        fullWidth
                                        id="name"
                                        name="name"
                                        autoComplete="name"
                                        autoFocus
                                        InputLabelProps={{ shrink: false }}
                                        placeholder="ID023659ADN"
                                        className="bg-gray-input"
                                    />
                                </Box>
                            </Grid>
                            <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingLeft: { sm: '1rem !important' }, paddingTop: { xs: '0rem !important', sm: '1rem !important' } }}>
                                <Box className="bg-gray-input">
                                    <label style={{ display: 'block' }}>Created on</label>
                                    <LocalizationProvider dateAdapter={AdapterDayjs}>
                                        <DatePicker format="DD/MM/YYYY" />
                                    </LocalizationProvider>
                                </Box>
                            </Grid>
                        </Grid>
                        <Grid container spacing={2} className='asset-popup'>
                            <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingRight: { sm: '1rem !important' } }}>
                                <Box>
                                    <label style={{ display: 'block' }}>Department</label>
                                    <TextField
                                        margin="normal"
                                        required
                                        fullWidth
                                        id="name"
                                        name="name"
                                        autoComplete="name"
                                        autoFocus
                                        InputLabelProps={{ shrink: false }}
                                        placeholder="Physics"
                                        className="bg-gray-input"
                                    />
                                </Box>
                            </Grid>
                            <Grid item xs={12} sm={6} md={6} lg={6} sx={{ paddingLeft: { sm: '1rem !important' }, paddingTop: { xs: '0rem !important', sm: '1rem !important' } }}>
                                <Box>
                                    <label style={{ display: 'block' }}>Laboratory</label>
                                    <TextField
                                        margin="normal"
                                        required
                                        fullWidth
                                        id="name"
                                        name="name"
                                        autoComplete="name"
                                        autoFocus
                                        InputLabelProps={{ shrink: false }}
                                        placeholder="Mechanical"
                                        className="bg-gray-input"
                                    />
                                </Box>
                            </Grid>
                        </Grid>
                        <Grid container spacing={2} className='asset-popup'>
                            <Grid item xs={12} sm={12} md={12} lg={12}>
                                <Box>
                                    <label style={{ display: 'block' }}>Procedure name<span style={{ color: '#E2445C' }}>*</span></label>
                                    <FormControl sx={{ width: "100%" }}>
                                        <Select
                                            labelId="tselect-popup-label"
                                            id="select-popup"
                                            value={answers}
                                            displayEmpty
                                            IconComponent={ExpandMoreOutlinedIcon}
                                            onChange={(event) => setAnswers(event.target.value)}
                                            renderValue={
                                                answers !== ""
                                                    ? undefined
                                                    : () => <Placeholder>Organisation</Placeholder>
                                            }
                                        >
                                            <MenuItem value={"1"}>1</MenuItem>
                                            <MenuItem value={"2"}>2</MenuItem>
                                            <MenuItem value={"3"}>3</MenuItem>
                                        </Select>
                                    </FormControl>
                                </Box>
                            </Grid>
                        </Grid>
                        <Grid container spacing={2} className='asset-popup'>
                            <Grid item xs={12} sm={12} md={12} lg={12}>
                                <Box>
                                    <label style={{ display: 'block' }}>Test objective</label>
                                    <TextField
                                        margin="normal"
                                        required
                                        fullWidth
                                        id="name"
                                        name="name"
                                        autoComplete="name"
                                        autoFocus
                                        InputLabelProps={{ shrink: false }}
                                        placeholder="Test objective"
                                    />
                                </Box>
                            </Grid>
                        </Grid>
                        <Grid container spacing={2} className='asset-popup calender-sec'>
                            <Grid item xs={12} sm={6} md={6} lg={6}>
                                <Box>
                                    <label style={{ display: 'block' }}>Set due date</label>
                                    <LocalizationProvider dateAdapter={AdapterDayjs}>
                                        <DatePicker format="DD/MM/YYYY" />
                                    </LocalizationProvider>
                                </Box>
                            </Grid>
                        </Grid>
                        <Grid container spacing={2} className='asset-popup'>
                            <Grid item xs={12} sm={12} md={12} lg={12}>
                                <Box>
                                    <label style={{ display: 'block', marginBottom: '0.8rem' }}>Assign to</label>
                                    <Box sx={{ display: 'flex', alignItems: 'center' }}>
                                        <img src={Avatars} alt='Avatars' />
                                        <Button
                                            type="submit"
                                            variant="contained"
                                            className="avatar-add"
                                            onClick={() => {
                                                setRunzOpen(true);
                                            }}
                                        >
                                            <AddIcon sx={{ mr: 1 }} />
                                            Add
                                        </Button>
                                    </Box>
                                </Box>
                            </Grid>
                        </Grid>
                    </Box>
                    <Box sx={{ display: { xs: "block", sm: 'flex' }, justifyContent: 'flex-end', mt: 3 }}>
                        <Button type="submit" variant="contained" onClick={() => { openConfirmationPopup(true) }} className="cancel-btn">Cancel</Button>
                        <Button type="submit" variant="contained" onClick={submitFormPopup} className="add-btn">Create</Button>
                    </Box>
                </Box>
            </Dialog>
            <Box>
                <AddPeoplePopup
                    open={runzOpen}
                    close={() => setRunzOpen(false)}
                />
            </Box>
        </div>
    )
}
);
export default RunzForm;